apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: kong-cp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kong
    app.kubernetes.io/version: "3.6"
    enable-metrics: "true"
    helm.sh/chart: kong-2.40.0
  name: kong-controlplane-admin
  namespace: kong-mawan-new
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  externalIPs:
  - 192.168.1.3
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: kong-manager
    port: 8002
    protocol: TCP
    targetPort: 8002
  - name: kong-admin
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: kong-cp
    app.kubernetes.io/name: kong
  sessionAffinity: None
  type: LoadBalancer